/*
 * This file is generated by jOOQ.
 */
package eugene.korovkin.stocks.jooq.tables.records;


import eugene.korovkin.stocks.jooq.tables.Company;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> implements Record5<UUID, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stocks.company.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>stocks.company.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>stocks.company.symbol</code>.
     */
    public void setSymbol(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stocks.company.symbol</code>.
     */
    public String getSymbol() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stocks.company.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stocks.company.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stocks.company.industry</code>.
     */
    public void setIndustry(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stocks.company.industry</code>.
     */
    public String getIndustry() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stocks.company.sector</code>.
     */
    public void setSector(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stocks.company.sector</code>.
     */
    public String getSector() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Company.COMPANY.ID;
    }

    @Override
    public Field<String> field2() {
        return Company.COMPANY.SYMBOL;
    }

    @Override
    public Field<String> field3() {
        return Company.COMPANY.NAME;
    }

    @Override
    public Field<String> field4() {
        return Company.COMPANY.INDUSTRY;
    }

    @Override
    public Field<String> field5() {
        return Company.COMPANY.SECTOR;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSymbol();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getIndustry();
    }

    @Override
    public String component5() {
        return getSector();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSymbol();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getIndustry();
    }

    @Override
    public String value5() {
        return getSector();
    }

    @Override
    public CompanyRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public CompanyRecord value2(String value) {
        setSymbol(value);
        return this;
    }

    @Override
    public CompanyRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public CompanyRecord value4(String value) {
        setIndustry(value);
        return this;
    }

    @Override
    public CompanyRecord value5(String value) {
        setSector(value);
        return this;
    }

    @Override
    public CompanyRecord values(UUID value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyRecord
     */
    public CompanyRecord() {
        super(Company.COMPANY);
    }

    /**
     * Create a detached, initialised CompanyRecord
     */
    public CompanyRecord(UUID id, String symbol, String name, String industry, String sector) {
        super(Company.COMPANY);

        setId(id);
        setSymbol(symbol);
        setName(name);
        setIndustry(industry);
        setSector(sector);
    }
}
