/*
 * This file is generated by jOOQ.
 */
package eugene.korovkin.stocks.jooq;


import eugene.korovkin.stocks.jooq.tables.Company;
import eugene.korovkin.stocks.jooq.tables.Position;
import eugene.korovkin.stocks.jooq.tables.records.CompanyRecord;
import eugene.korovkin.stocks.jooq.tables.records.PositionRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * stocks.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CompanyRecord> COMPANY_PKEY = Internal.createUniqueKey(Company.COMPANY, DSL.name("company_pkey"), new TableField[] { Company.COMPANY.ID }, true);
    public static final UniqueKey<PositionRecord> POSITION_PKEY = Internal.createUniqueKey(Position.POSITION, DSL.name("position_pkey"), new TableField[] { Position.POSITION.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PositionRecord, CompanyRecord> POSITION__POSITION_COMPANY_ID_FKEY = Internal.createForeignKey(Position.POSITION, DSL.name("position_company_id_fkey"), new TableField[] { Position.POSITION.COMPANY_ID }, Keys.COMPANY_PKEY, new TableField[] { Company.COMPANY.ID }, true);
}
