/*
 * This file is generated by jOOQ.
 */
package eugene.korovkin.stocks.jooq;


import eugene.korovkin.stocks.jooq.tables.Company;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stocks extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stocks</code>
     */
    public static final Stocks STOCKS = new Stocks();

    /**
     * The table <code>stocks.company</code>.
     */
    public final Company COMPANY = Company.COMPANY;

    /**
     * No further instances allowed
     */
    private Stocks() {
        super("stocks", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Company.COMPANY);
    }
}
