/*
 * This file is generated by jOOQ.
 */
package eugene.korovkin.stocks.jooq;


import eugene.korovkin.stocks.jooq.tables.Company;
import eugene.korovkin.stocks.jooq.tables.Position;


/**
 * Convenience access to all tables in stocks.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stocks.company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>stocks.position</code>.
     */
    public static final Position POSITION = Position.POSITION;
}
